#pragma once

#define VERSION_MAJOR 1
#define VERSION_MINOR 0
#define VERSION_BUILD 
#define VERSION_REVISION 1

#define VERSION_PRODUCTNAME_VALUE "Auto Nice"
#define VERSION_COMPANYNAME_VALUE "markdevel"
#define VERSION_LEGALCOPYRIGHT_VALUE "Copyright (c) 2013 markdevel"
#define VERSION_LEGALTRADEMARK_VALUE "All Rights Reserved."
#define VERSION_VALUE "1.0..1"

#define BINARY_VERSION 1,0,,1

#define VERSION_FILEVERSION BINARY_VERSION
#define VERSION_PRODUCTVERSION BINARY_VERSION
#define VERSION_FILEVERSION_VALUE VERSION_VALUE
#define VERSION_PRODUCTVERSION_VALUE VERSION_VALUE
